server:
  port: 80
spring:
  application:
    name: lk-user-consumer
#  cloud:
#    loadbalancer:
#      retry:
#        enabled: true # 开启Spring Cloud的重试功能
##日志级别
#logging:
#  level:
#    com.leyou: debug
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka
#  instance:
#    prefer-ip-address: true
#    ip-address: 127.0.0.1
#lk-user-server:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#    ConnectTimeout: 250 # Ribbon的连接超时时间
#    ReadTimeout: 1000 # Ribbon的数据读取超时时间
#    OkToRetryOnAllOperations: true # 是否对所有操作都进行重试
#    MaxAutoRetriesNextServer: 1 # 切换实例的重试次数
#    MaxAutoRetries: 1 # 对当前实例的重试次数
#feign:
#  hystrix:
#    enabled: true # 开启Feign的熔断功能
#  compression:
#    request:
#      enabled: true # 开启请求压缩
#      mime-types: text/html,application/xml,application/json # 设置压缩的数据类型
#      min-request-size: 2048 # 设置触发压缩的大小下限
#    response:
#      enabled: true # 开启响应压缩
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMillisecond: 6000 # 设置hystrix的超时时间为6000ms
