server:
  port: 81
spring:
  application:
    name: lk-user-server
mybatis:
  type-aliases-package: com.lk.userserver.pojo
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
